### ISSUE TITLE
How to test your network?

### ISSUE THREAD

**Issue by lukkio88** [WangYueFt/prnet#6]
Hi,

I would like to try your network, but the readme doesn't explain how to run it, but just how to train it.
Could you please provide a brief explanation on how to use it?

Regards

**Comment by SebastianGrans** [comment]
The author hasn't provided that code. 
Here's my fork with were I've implemented that: [Link](https://github.com/SebastianGrans/prnet) 

In `main()` of `main.py` I there's some code for applying the network to point clouds. 

In that fork you can also find a pre-trained model which Wang hasn't (He mentioned he lost it).
All my contributions to that code are kinda messy because it's currently being worked on. 

Hope that helps :)

**Comment by lukkio88** [comment]
I'll give it a go!!! Thank you!!!

**Comment by WangYueFt** [comment]
> The author hasn't provided that code.
> Here's my fork with were I've implemented that: [Link](https://github.com/SebastianGrans/prnet)
> 
> In `main()` of `main.py` I there's some code for applying the network to point clouds.
> 
> In that fork you can also find a pre-trained model which Wang hasn't (He mentioned he lost it).
> All my contributions to that code are kinda messy because it's currently being worked on.
> 
> Hope that helps :)

Thanks for the answer and code :-)
